DROP TABLE BATTLE;
DROP TABLE TRADING;
DROP TABLE TRADINGOFFER;
DROP TABLE DECK;
DROP TABLE PACKAGE;
DROP TABLE STACK;
DROP TABLE CARDS;
DROP TABLE AUTH_TOKENS;
DROP TABLE USERS;

DELETE FROM BATTLE WHERE TRUE;
DELETE FROM TRADINGOFFER WHERE TRUE;
DELETE FROM DECK WHERE TRUE;
DELETE FROM PACKAGE WHERE TRUE;
DELETE FROM STACK WHERE TRUE;
DELETE FROM CARDS WHERE TRUE;
DELETE FROM AUTH_TOKENS WHERE TRUE;
DELETE FROM USERS WHERE TRUE;
